"""add compliance_alerts column

Revision ID: b6d6b0c98cdd
Revises: 92c183c6664a
Create Date: 2026-09-08 16:19:53.842938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d6b0c98cdd'
down_revision: Union[str, Sequence[str], None] = '92c183c6664a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'document_analyses',
        sa.Column('compliance_alerts', sa.Text(), nullable=False, server_default='[]'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_analyses', 'compliance_alerts')
    # ### end Alembic commands ###
