import { useState, useEffect } from "react";
import UploadDocument from "../components/UploadDocument";
import { api, friendlyError } from "../services/api";
import type { DocumentRecord, InvoiceExtraction, InvoiceCompliance } from "../services/api";

type Props = { token: string; documents: DocumentRecord[]; loading: boolean; error: string; onRefresh: () => void; onLogout: () => void };

export default function Dashboard({ token, documents, loading, error, onRefresh, onLogout }: Props) {
  const [selected, setSelected] = useState<DocumentRecord | null>(null);
  const [busy, setBusy] = useState("");
  const [actionError, setActionError] = useState("");
  const completed = documents.filter(d => d.status === "completed").length;
  const processing = documents.filter(d => d.status === "processing").length;
  const failed = documents.filter(d => d.status === "failed").length;
  const pending = documents.filter(d => d.status === "uploaded" || d.status === "pending").length;
  async function run(action: "process" | "analyze" | "delete", doc: DocumentRecord) {
    if (action === "delete" && !window.confirm(`Delete ${doc.filename}?`)) return;
    setBusy(`${action}-${doc.id}`); setActionError("");
    try { if (action === "process") await api.process(doc.id, token); if (action === "analyze") await api.analyze(doc.id, token); if (action === "delete") await api.remove(doc.id, token); await onRefresh(); if (selected?.id === doc.id && action === "delete") setSelected(null); }
    catch (err) { setActionError(friendlyError(err)); } finally { setBusy(""); }
  }
  return <div className="app-shell"><aside className="sidebar"><div className="logo-lockup"><div className="brand-mark small">D</div><div><strong>DOCUMIND</strong><span>AI PLATFORM</span></div></div><nav><a className="active">⌂ <span>Overview</span></a><a>▣ <span>Documents</span></a><a>◈ <span>AI Processing</span></a><a>◌ <span>Audit logs</span></a></nav><div className="sidebar-foot"><span className="online-dot" /> System operational<button onClick={onLogout}>Sign out</button></div></aside><main className="workspace"><header className="topbar"><div><p className="eyebrow">WORKSPACE / OVERVIEW</p><h1>Good morning, welcome back</h1></div><div className="user-chip"><span>U</span><div><strong>Workspace user</strong><small>Employee account</small></div><button onClick={onLogout}>Logout</button></div></header><div className="content"><div className="hero-row"><div><p className="eyebrow cyan">INTELLIGENT DOCUMENT OPERATIONS</p><h2>Your document command center</h2><p className="muted">Ingest, understand, and act on your business content.</p></div><div className="hero-pulse"><span className="pulse-dot" /> AI services ready</div></div>{(error || actionError) && <div className="alert wide">{error || actionError}</div>}<section className="metric-grid"><Metric label="Total documents" value={documents.length} tone="blue" /><Metric label="Completed" value={completed} tone="green" /><Metric label="In progress" value={processing} tone="amber" /><Metric label="Needs attention" value={failed} tone="red" /></section><div className="main-grid"><UploadDocument token={token} onUploaded={() => onRefresh()} /><section className="panel"><div className="panel-heading"><div><p className="eyebrow">LIVE WORKSPACE</p><h3>Recent documents</h3></div><span className="count-pill">{documents.length} total</span></div>{loading ? <div className="empty-state"><span className="spinner" />Loading workspace data...</div> : documents.length === 0 ? <div className="empty-state"><div className="empty-icon">□</div><strong>No documents yet</strong><span>Upload a document to start your intelligence workflow.</span></div> : <div className="document-list">{documents.map(doc => <DocumentRow key={doc.id} doc={doc} busy={busy} onAction={run} onView={setSelected} />)}</div>}</section></div><section className="pipeline panel"><div><p className="eyebrow">PROCESSING PIPELINE</p><h3>From file to insight</h3></div><div className="pipeline-steps">{["Upload", "Extract", "Analyze", "Validate", "Act"].map((step, index) => <div className="pipeline-step" key={step}><span>{String(index + 1).padStart(2, "0")}</span><strong>{step}</strong>{index < 4 && <i />}</div>)}</div><small>{pending} document{pending === 1 ? "" : "s"} ready for processing</small></section></div></main>{selected && <Detail doc={selected} token={token} onClose={() => setSelected(null)} />}</div>;
}
function Metric({ label, value, tone }: { label: string; value: number; tone: string }) { return <div className={`metric-card ${tone}`}><span>{label}</span><strong>{value}</strong><small>Live workspace count</small></div>; }
function DocumentRow({ doc, busy, onAction, onView }: { doc: DocumentRecord; busy: string; onAction: (action: "process" | "analyze" | "delete", doc: DocumentRecord) => void; onView: (doc: DocumentRecord) => void }) { const canProcess = doc.status === "uploaded" || doc.status === "pending" || doc.status === "failed"; const canAnalyze = doc.status === "completed"; return <div className="document-row"><div className="file-icon">{doc.file_type.includes("pdf") ? "PDF" : doc.file_type.includes("word") ? "DOC" : "IMG"}</div><div className="doc-main"><strong title={doc.filename}>{doc.filename}</strong><small>{formatBytes(doc.file_size)} · {new Date(doc.created_at).toLocaleDateString()}</small></div><span className={`status ${doc.status}`}><i />{doc.status}</span><div className="row-actions"><button onClick={() => onView(doc)}>View</button>{canProcess && <button disabled={!!busy} onClick={() => onAction("process", doc)}>{busy === `process-${doc.id}` ? "..." : "Process"}</button>}{canAnalyze && <button className="accent" disabled={!!busy} onClick={() => onAction("analyze", doc)}>{busy === `analyze-${doc.id}` ? "..." : "Analyze"}</button>}<button className="danger" disabled={!!busy} onClick={() => onAction("delete", doc)}>Delete</button></div></div>; }
function Detail({ doc, token, onClose }: { doc: DocumentRecord; token: string; onClose: () => void }) {
  const [text, setText] = useState<string | null>(null); const [analysis, setAnalysis] = useState<Awaited<ReturnType<typeof api.analysis>> | null>(null); const [invoice, setInvoice] = useState<InvoiceExtraction | null>(null); const [compliance, setCompliance] = useState<InvoiceCompliance | null>(null); const [invoiceError, setInvoiceError] = useState(""); const [complianceError, setComplianceError] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const load = async () => { setLoading(true); setError(""); setInvoiceError(""); setComplianceError(""); try { const [textResult, analysisResult] = await Promise.allSettled([api.text(doc.id, token), api.analysis(doc.id, token)]); if (textResult.status === "fulfilled") setText(textResult.value.extracted_text); else setError("Could not load extracted text. Process the document first."); if (analysisResult.status === "fulfilled") { setAnalysis(analysisResult.value); if (analysisResult.value.document_type === "Invoice") { try { setInvoice(await api.invoiceExtraction(doc.id, token)); } catch (err) { setInvoice(null); setInvoiceError(friendlyError(err)); } try { setCompliance(await api.invoiceCompliance(doc.id, token)); } catch (err) { setCompliance(null); setComplianceError(friendlyError(err)); } } } } catch (err) { setError(friendlyError(err)); } finally { setLoading(false); } };
  useEffect(() => { if (doc.status === "completed" || doc.status === "processing") void load(); }, [doc.id, doc.status, token]);
  return <div className="modal-backdrop"><section className="detail-modal"><button className="close-button" onClick={onClose}>×</button><p className="eyebrow cyan">DOCUMENT DETAIL</p><h2>{doc.filename}</h2><div className="detail-meta"><span className={`status ${doc.status}`}><i />{doc.status}</span><span>{doc.file_type}</span><span>{formatBytes(doc.file_size)}</span><span className="uploaded-date">{new Date(doc.created_at).toLocaleDateString()} {new Date(doc.created_at).toLocaleTimeString()}</span></div>{doc.status === "uploaded" && <div className="alert info">ⓘ Process this document to extract text and generate AI analysis.</div>}{doc.status === "failed" && <div className="alert error">⚠ This document failed to process. Please try again or upload a different file.</div>}{!text && !analysis && !error && doc.status === "completed" && <button className="secondary-button" disabled={loading} onClick={() => void load()}>{loading ? "Loading..." : "Load extracted intelligence"}</button>}{error && <div className="alert">{error}</div>}{text && <div className="detail-section"><h3>Extracted text</h3><pre>{text}</pre></div>}{analysis && <div className="detail-section"><h3>AI analysis <span className="type-badge">{analysis.document_type}</span></h3>{analysis.document_type === "Invoice" && <InvoiceFields invoice={invoice} fallback={analysis} error={invoiceError} compliance={compliance} complianceError={complianceError} />} {analysis.document_type === "Resume" && <ResumeFields analysis={analysis} />}<h4>Summary</h4><p>{analysis.summary}</p><h4>Key points</h4><pre>{analysis.key_points}</pre><h4>Important information</h4><pre>{analysis.important_information}</pre></div>}</section></div>;
}
function InvoiceFields({ invoice, fallback, error, compliance, complianceError }: { invoice: InvoiceExtraction | null; fallback: Awaited<ReturnType<typeof api.analysis>>; error: string; compliance: InvoiceCompliance | null; complianceError: string }) {
  const f = invoice?.fields; const money = (value: number | null | undefined) => value == null ? null : `${f?.currency || ""} ${value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`.trim();
  return <div className="extracted-fields"><h4>Structured Invoice Fields</h4>{!f && !error && <div className="alert info">Loading structured invoice extraction...</div>}{error && <div className="alert error">Structured invoice extraction failed: {error}</div>}<div className="field-grid"><Field label="Invoice Number" value={f?.invoice_number || fallback.invoice_number} /><Field label="Invoice Date" value={f?.invoice_date || fallback.invoice_date} /><Field label="Vendor" value={f?.vendor_name || fallback.vendor} /><Field label="Vendor GSTIN" value={f?.vendor_gstin} /><Field label="Buyer" value={f?.buyer_name} /><Field label="Buyer GSTIN" value={f?.buyer_gstin} /><Field label="PO Number" value={f?.po_number} /><Field label="Due Date" value={f?.due_date} /><Field label="Currency" value={f?.currency} /><Field label="Subtotal" value={money(f?.subtotal)} /><Field label="Total Tax" value={money(f?.tax_amount)} /><Field label="Total Amount" value={money(f?.total_amount) || fallback.total_amount} /></div>{f?.tax_breakdown?.length ? <><h4>Tax Breakdown</h4><div className="invoice-table-wrap"><table className="invoice-table"><thead><tr><th>Tax</th><th>Rate</th><th>Amount</th></tr></thead><tbody>{f.tax_breakdown.map((tax, i) => <tr key={`${tax.tax_type}-${i}`}><td>{tax.tax_type}</td><td>{tax.rate == null ? "—" : `${tax.rate}%`}</td><td>{money(tax.amount) || "—"}</td></tr>)}</tbody></table></div></> : null}{f?.line_items?.length ? <><h4>Line Items</h4><div className="invoice-table-wrap"><table className="invoice-table"><thead><tr><th>#</th><th>Description</th><th>HSN</th><th>Qty</th><th>Unit Price</th><th>Amount</th></tr></thead><tbody>{f.line_items.map((item, i) => <tr key={`${item.line_number}-${i}`}><td>{item.line_number ?? i + 1}</td><td>{item.description || "—"}</td><td>{item.hsn_code || "—"}</td><td>{item.quantity ?? "—"}</td><td>{money(item.unit_price) || "—"}</td><td>{money(item.amount) || "—"}</td></tr>)}</tbody></table></div></> : null}<CompliancePanel compliance={compliance} error={complianceError} /></div>;
}
function CompliancePanel({ compliance, error }: { compliance: InvoiceCompliance | null; error: string }) { if (error) return <div className="compliance-panel"><div className="compliance-head"><div><p className="eyebrow">VALIDATION</p><h4>Compliance Checks</h4></div></div><div className="alert error">Compliance validation failed: {error}</div></div>; if (!compliance) return <div className="compliance-panel"><div className="compliance-head"><div><p className="eyebrow">VALIDATION</p><h4>Compliance Checks</h4></div></div><div className="alert info">Loading compliance checks...</div></div>; return <div className="compliance-panel"><div className="compliance-head"><div><p className="eyebrow">VALIDATION</p><h4>Compliance Checks</h4></div><span className={`compliance-status ${compliance.overall_status.toLowerCase()}`}>{compliance.overall_status.replaceAll("_", " ")}</span></div><div className="compliance-stats"><span>Passed <strong>{compliance.passed}</strong></span><span>Warnings <strong>{compliance.warnings}</strong></span><span>Failed <strong>{compliance.failed}</strong></span></div><div className="compliance-list">{compliance.checks.map(check => <div className="compliance-row" key={check.rule}><span className={`compliance-icon ${check.status.toLowerCase()}`}>{check.status === "PASS" ? "✓" : check.status === "WARNING" ? "!" : "×"}</span><div><strong>{check.rule.replaceAll("_", " ")}</strong><small>{check.message}</small></div><b className={check.status.toLowerCase()}>{check.status}</b></div>)}</div></div>; }
function hasValue(value: unknown): boolean { if (value === null || value === undefined) return false; const normalized = String(value).trim().toLowerCase(); return normalized !== "" && normalized !== "n/a" && normalized !== "na" && normalized !== "not available" && normalized !== "null" && normalized !== "undefined"; }
function Field({ label, value }: { label: string; value: string | number | null | undefined }) { if (!hasValue(value)) return null; return <div className="field-item"><span>{label}</span><strong>{value}</strong></div>; }
function ResumeFields({ analysis }: { analysis: Awaited<ReturnType<typeof api.analysis>> }) { return <div className="extracted-fields"><h4>Extracted Fields</h4><div className="field-grid">{hasValue(analysis.full_name) && <Field label="Full Name" value={analysis.full_name} />}{hasValue(analysis.date_of_birth) && <Field label="Date of Birth" value={analysis.date_of_birth} />}{hasValue(analysis.email) && <Field label="Email" value={analysis.email} />}{hasValue(analysis.phone) && <Field label="Phone" value={analysis.phone} />}{hasValue(analysis.education) && <Field label="Education" value={analysis.education} />}{hasValue(analysis.skills) && <Field label="Skills" value={analysis.skills} />}{hasValue(analysis.experience) && <Field label="Experience" value={analysis.experience} />}{hasValue(analysis.height) && <Field label="Height" value={analysis.height} />}{hasValue(analysis.father_name) && <Field label="Father Name" value={analysis.father_name} />}{hasValue(analysis.father_occupation) && <Field label="Father Occupation" value={analysis.father_occupation} />}{hasValue(analysis.mother_occupation) && <Field label="Mother Occupation" value={analysis.mother_occupation} />}{hasValue(analysis.siblings) && <Field label="Siblings" value={analysis.siblings} />}</div></div>; }
function formatBytes(bytes: number) { if (!bytes) return "0 B"; const units = ["B", "KB", "MB"]; const index = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1); return `${(bytes / 1024 ** index).toFixed(index ? 1 : 0)} ${units[index]}`; }
